# Site settings
title: "Tiqit"
description: "Tiqit"
url: "https://ai-sf.it/tiqit23"
destination: ../site/
locale: "it"

# Build settings
markdown: kramdown
future: true
permalink: /blog/:year/:month/:day/:title/
destination: _site


#facebook
fb_admins:
fb_appid:

#Collections
collections:
  events:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

#plugins:
# - jekyll-redirect-from
# - jekyll-sitemap
